/* sys/defs.h */

/* Copyright (c) 2024 Peter Welch
   All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions are met:

   * Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above copyright
     notice, this list of conditions and the following disclaimer in
     the documentation and/or other materials provided with the
     distribution.
   * Neither the name of the copyright holders nor the names of
     contributors may be used to endorse or promote products derived
     from this software without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef _DEFS_H_
#define _DEFS_H_

#include <stddef.h>

//#include "sys/errno.h"

#define PUBLIC
#define PRIVATE static

#define FALSE 0
#define TRUE 1

#define NIL  '\0'

#define MIN(j,k) ((j) < (k) ? (j) : (k))
#define MAX(j,k) ((j) > (k) ? (j) : (k))
#define isodd(i) ((i) & 1)

typedef unsigned char uchar_t;
typedef unsigned short ushort_t;
typedef unsigned long ulong_t;
typedef uchar_t bool_t;
typedef uchar_t hostid_t;
typedef void * jobref_t;
typedef void (*Ptf) (void);
typedef long off_t;

/* Declare a pointer to a function that takes a uchar_t pointer as its sole
 * argument and returns a uchar_t value. The argument is populated with a
 * value, and a result of the operation is returned. The argument must not
 * be null. It is used by [app]/inp.c to consume from either SER or ISTREAM.
 */
typedef uchar_t (*CharProc) (char *cp);

/* no LED */

/* Adjust to suit whatever pin your hardware uses to enter the bootloader */
#define BL_PIN  PIND                /* 0x29 */
#define BL_DDR  DDRD                /* 0x2A */
#define BL_PORT PORTD               /* 0x2B */
#define BL      PIND6               /* 0x06 */

/* An external reset is generated by outputting a low-Z zero at pin D7.
 * The extrst pin should emulate an open drain.
 * The initial condition has both PORTD7 and DDD7 at zero which configures
 * pin D7 as a high-Z input with no pullup.
 * It is activated by setting DDD7 high which remains in effect until it
 * is released by the reset mechanism which restores the initial condition.
 */
#define EXTRST_DDR  DDRD
#define EXTRST_BIT  _BV(DDD7)
#define generate_external_reset()   (EXTRST_DDR |= EXTRST_BIT)

/* arbitrary values for timer selection in host.h for clk.c and stw.c */ 
#define TIMER0 0 
#define TIMER1 1
#define TIMER2 2

#endif /* _DEFS_H_ */
