#!/usr/bin/env php
<?php

/*
 barometer-3col - process comma separated hex variables.
            time, type, temperature << 22 | pressure & 0x003FFFFF
            input:  61EEA2D1,06,2E019427

            output:-
                    Day Dom Mon Time TZ Year Temperature Pressure
                    Sun 17 Jul 22:43:14 BST 2022 66.38 29.849

     usage: grep -E ^be,[[:xdigit:]]{8},[[:xdigit:]]{2},[[:xdigit:]]{8}$ \
                  `ls -rt ../tmp/maple*|tail -1`|cut -c2- | \
                   cat ../legacy/BMP180-feb-may-2022 - | \
                   sort|uniq|./barometer-8col
*/

class ProcCsv {

    function main($argv, $argc) {
        $ctime = 0;
        $type = 0;
        $temppres = 0;
        $units = 1; /* 0= C and millibars, 1= F and inHg. */ 
        print("Day Dom Mon Time TZ Year Temperature Pressure\n");
        while ($str = fgets(STDIN)) {
            if (list($s1, $s2, $s3) = explode(',', $str)) {
                $ctime = hexdec($s1);
                $type = hexdec($s2);
                $temppres = hexdec($s3);
                if ($type == 6) {
                    print(strftime("%a %e %b %H:%M:%S %Z %Y ", $ctime));
                    if ($units) {
                        printf("%.2f ", ($temppres >> 22) * 0.18 + 32);
                        printf("%.3f\n", ($temppres & 0x003FFFFF) / 
                                                          3386.3886666667);
                    } else {
                        printf("%.2f ", ($temppres >> 22) / 10.0);
                        printf("%.3f\n", ($temppres & 0x003FFFFF) / 100.0);
                    }
                }
            }
        }
    }
}

$foo = new ProcCsv;
$foo->main($argv, $argc);
?>
