#!/usr/bin/env php
<?php

/*
 showtime - print the current oslo UTC 

        usage:  showtime >$port
*/

class Showtime {

    function main($argv, $argc) {
        $prev = time();
        while (1) {
            $now = time();
            if ($prev != $now) {
                echo "date\n";
                $prev = $now;
            }
        }
    }
}

$foo = new Showtime;
$foo->main($argv, $argc);
?>
